### ISSUE TITLE
import event dispatch

### ISSUE THREAD

**Issue by krothmuller** [plentico/plenti#92] opened 2020-12-14 18:47 UTC
In "regular" Svelte apps, dispatching events from components is done by per the docs:

import { createEventDispatcher } from 'svelte';
const dispatch = createEventDispatcher();

then using dispatch('eventName', {parms})

but I hand to use: import { createEventDispatcher } from "svelte/internal";

While I haven't used the life cycle events also usie the from "svelte" reference - so that could be a problem as well?

**Comment by jimafisk** [comment] 2020-12-14 19:05
Hi @krothmuller, you are 100% correct, this is a bug I'm aware of: https://github.com/plentico/plenti/issues/38.

In the short term you can get around this exactly like you did by using the more specific `"svelte/internal"` rather than just `"svelte"`, but since the Svelte docs reference the shorthand version so often I imagine folks are going to continuously run into this issue and not everyone will figure what the problem is like you were able to do. I should be able to extend Gopack to accommodate this, so I'll take a look. Thanks for flagging!

**Comment by krothmuller** [comment] 2020-12-14 19:53
Yes.. it threw me at first when I got the error… thought I did something wrong, but… then did a little search and found where it was defined.

BUT YES - everyone is going to make the assumption that you have just provided a compilation system for “standard” svelte. Guess I should have looked into issues… it is also “below” the fold - second page… and my issues as a better name for those looking for it ;) -since event stuff is probably on of the most common usage of the “svelte” name space.

Cheers,

Ken

P.S. will respond to the other issue as well

**Comment by jimafisk** [comment] 2020-12-14 20:08
Totally agree @krothmuller, this needs to get fixed. The issue I made is buried at this point, even took me a minute to find it. I'm glad you stuck with it and made this bug report, but we'll definitely lose some folks out of frustration unless we address it so thanks for resurfacing!

**Comment by jimafisk** [comment] 2021-01-22 04:28
Fixed in [v0.3.15](https://github.com/plentico/plenti/releases/tag/v0.3.15). Just let me know if it still gives you trouble! Thanks!

**Closed by jimafisk** 2021-01-22 04:28 UTC
Labels: bug, high
